ALTER TYPE "OptionDisplayType" ADD VALUE IF NOT EXISTS 'CASCADE';

ALTER TABLE "OptionGroup" ADD COLUMN IF NOT EXISTS "facetALabel" TEXT;
ALTER TABLE "OptionGroup" ADD COLUMN IF NOT EXISTS "facetBLabel" TEXT;

ALTER TABLE "OptionItem" ADD COLUMN IF NOT EXISTS "facetA" TEXT;
ALTER TABLE "OptionItem" ADD COLUMN IF NOT EXISTS "facetB" TEXT;
